import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Script from "next/script";
import BootstrapClient from "./component/BootstrapClient";
import Navbar from "./component/Navbar";
import HeroHeader from "./component/Header";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sofiaPro = localFont({
  src: [
    {
      path: "../../src/fonts/sofia-pro/SofiaPro-Regular.woff2",
      weight: "400",
    },
    {
      path: "../../src/fonts/sofia-pro/SofiaPro-Bold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-sofia-pro",
});

export const metadata = {
  title: "Thirunar Archives",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sofiaPro.variable}`}
      >
        <BootstrapClient />
        <Navbar />
        <HeroHeader />
        {children}
        <Footer />
        <Script
          src="https://kit.fontawesome.com/a076d05399.js"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}